avasolos/accounts/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'avasolos.accounts.views.dashboard', 
        name='dashboard'),
    url(r'^entrar/$', 'django.contrib.auth.views.login', 
        {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^sair/$', 'django.contrib.auth.views.logout', 
        {'next_page': 'core:home'}, name='logout'),
    url(r'^cadastre-se/$', 'avasolos.accounts.views.register', 
        name='register'),
    url(r'^nova-senha/$', 'avasolos.accounts.views.password_reset', 
        name='password_reset'),
    url(r'^confirmar-nova-senha/(?P<key>\w+)/$', 
        'avasolos.accounts.views.password_reset_confirm', 
        name='password_reset_confirm'),
    url(r'^editar/$', 'avasolos.accounts.views.edit', 
        name='edit'),
    url(r'^editar-senha/$', 'avasolos.accounts.views.edit_password', 
        name='edit_password'),
)

avasolos/core/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('avasolos.core.views',
    url(r'^$', 'home', name='home'),
    url(r'^contato/$', 'contact', name='contact'),
)

avasolos/forum/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('avasolos.forum.views',
    url(r'^$', 'index', name='index'),
    url(r'^tag/(?P<tag>[\w_-]+)/$', 'index', name='index_tagged'),
    url(r'^respostas/(?P<pk>\d+)/correta/$', 'reply_correct', 
        name='reply_correct'),
    url(r'^respostas/(?P<pk>\d+)/incorreta/$', 'reply_incorrect', 
        name='reply_incorrect'),
    url(r'^(?P<slug>[\w_-]+)/$', 'thread', name='thread'),
)

avasolos/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('avasolos.core.urls', namespace='core')),
    url(r'^conta/', include('avasolos.accounts.urls', namespace='accounts')),
    url(r'^turmas/', include('avasolos.turmas.urls', namespace='turmas')),
    url(r'^forum/', include('avasolos.forum.urls', namespace='forum')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

avasolos/core/models.py
from django.db import models

# Create your models here.

avasolos/core/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
    return render(request, 'home.html')

def contact(request):
    return render(request, 'contact.html')

avasolos/core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="AVA Solos - Uma simples plataforma de ensino aprendizagem" />
    <title>AVA Solos</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
</head>
<body>
<div class="header">
    <div class="home-menu pure-menu pure-menu-open pure-menu-horizontal pure-menu-fixed">
        <a class="pure-menu-heading" href="{% url 'core:home' %}">AVA SOLOS</a>
        <ul>
            <li class="pure-menu-selected"><a href="{% url 'core:home' %}">Início</a></li>
            <li><a href="{% url 'turmas:index' %}">Turmas</a></li>
            <li><a href="{% url 'forum:index' %}">Fórum</a></li>
            <li><a href="{% url 'core:contact' %}">Contato</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:dashboard' %}">Painel</a></li>
            <li><a href="{% url 'accounts:logout' %}">Sair</a></li>
            {% else %}
            <li><a href="{% url 'accounts:login' %}">Entrar</a></li>
            {% endif %}
        </ul>
    </div>
</div>
<div class="content">
    {% if messages %}
    <div class="pure-g-r content-ribbon">
        <aside class="pure-u-1">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        </aside>
    </div>
    {% endif %}
    {% block content %}{% endblock %}
    <div class="footer">
        AVA Solos - Uma simples plataforma de ensino aprendizagem
    </div>
</div>
<script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
{% block scripts %}{% endblock %}
</body>
</html>

avasolos/core/templates/contact.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h1>Fale conosco</h1>
        <p>Você pode entrar em contato conosco tanto por e-mail como pelas redes sociais, abaixo seguem os links para contato:</p>
        <h4>Links</h4>
        <ul>
            <li>E-mail: <a href="mailto:contato@avasolos.org">contato@avasolos.org</a></li>
            <li>Twitter: <a href="https://twitter.com/avasolos">@avasolos</a></li>
        </ul>
    </div>
</div>
{% endblock %}

avasolos/core/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    Uma Simples Plataforma de Ensino Aprendizagem
                </h1>
                <h2 class="splash-subhead">
                    O AVA Solos visa simplificar o ensino das disciplinas de tratamento de solos, provendo ferramentas objetivas e de fácil uso para os professores e alunos.
                </h2>
                <p>
                    <a href="#" class="pure-button primary-button">Saiba mais</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Vídeo-aulas e materiais digitais</h4>
            <h3>Publique suas aulas</h3>
            <p>
                O AVA Solos tem um sistema simples e prático para que o professor disponibilize vídeo-aulas e materiais digitais como: pdf's, slides, imagens ...
            </p>
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="http://placehold.it/400x250"
                 alt="Vídeo aulas e materiais digitais.">
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="http://placehold.it/400x250"
                 alt="Fórum de Dúvidas">
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Fórum de Dúvidas</h4>
            <h3>Interaja com seus Alunos</h3>
            <p>
                No AVA Solos você pode ter seu próprio sistema de fórum para que seus alunos possam interagir com você e com os outros alunos
            </p>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Exercícios</h4>
            <h3>Crie exercícios para avaliar seus alunos</h3>
            <p>
                Você pode criar exercícios para que os alunos possam ser avaliados e todo o controle de notas e resolução dos exercícios é controlado pela plataforma, facilitando sua vida
            </p>
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="http://placehold.it/400x250"
                 alt="Exercícios">
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="http://placehold.it/400x250"
                 alt="Mural de Avisos">
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Mural de Avisos</h4>
            <h3>Envie anúncios diretamente para os alunos</h3>
            <p>
                Organize os avisos do seu curso de forma fácil e simples.
            </p>
        </div>
    </div>
</div>
{% endblock %}