avasolos/turmas/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('avasolos.turmas.views',
    url(r'^$', 'index', name='index'),
    # url(r'^(?P<pk>\d+)/$', 'details', name='details'),
    url(r'^(?P<slug>[\w_-]+)/$', 'details', name='details'),
    url(r'^(?P<slug>[\w_-]+)/inscricao/$', 'enrollment', name='enrollment'),
    url(r'^(?P<slug>[\w_-]+)/cancelar-inscricao/$', 'undo_enrollment',
        name='undo_enrollment'),
    url(r'^(?P<slug>[\w_-]+)/anuncios/$', 'announcements',
        name='announcements'),
    url(r'^(?P<slug>[\w_-]+)/anuncios/(?P<pk>\d+)/$', 'show_announcement',
        name='show_announcement'),
    url(r'^(?P<slug>[\w_-]+)/aulas/$', 'lessons', name='lessons'),
    url(r'^(?P<slug>[\w_-]+)/aulas/(?P<pk>\d+)/$', 'lesson', name='lesson'),
    url(r'^(?P<slug>[\w_-]+)/materiais/(?P<pk>\d+)/$', 'material', name='material'),
)

avasolos/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('avasolos.core.urls', namespace='core')),
    url(r'^conta/', include('avasolos.accounts.urls', namespace='accounts')),
    url(r'^turmas/', include('avasolos.turmas.urls', namespace='turmas')),
    url(r'^forum/', include('avasolos.forum.urls', namespace='forum')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

avasolos/turmas/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

from avasolos.core.mail import send_mail_template


class TurmaManager(models.Manager):

    def search(self, query):
        return self.get_queryset().filter(
            models.Q(name__icontains=query) | \
            models.Q(description__icontains=query)
        )


class Turma(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Atalho')
    description = models.TextField('Descrição Simples', blank=True)
    about = models.TextField('Sobre a Turma', blank=True)
    start_date = models.DateField(
        'Data de Início', null=True, blank=True
    )
    image = models.ImageField(
        upload_to='turmas/images', verbose_name='Imagem',
        null=True, blank=True
    )

    created_at = models.DateTimeField('Criada em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizada em', auto_now=True)

    objects = TurmaManager()

    def __str__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('turmas:details', (), {'slug': self.slug})

    def release_lessons(self):
        today = timezone.now().date()
        return self.lessons.filter(release_date__gte=today)

    class Meta:
        verbose_name = 'Turma'
        verbose_name_plural = 'Turmas'
        ordering = ['name']


class Lesson(models.Model):

    name = models.CharField('Nome', max_length=100)
    description = models.TextField('Descrição', blank=True)
    number = models.IntegerField('Número (ordem)', blank=True, default=0)
    release_date = models.DateField('Data de Liberação', blank=True, null=True)

    turma = models.ForeignKey(Turma, verbose_name='Turma', related_name='lessons')

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def __str__(self):
        return self.name

    def is_available(self):
        if self.release_date:
            today = timezone.now().date()
            return self.release_date >= today
        return False

    class Meta:
        verbose_name = 'Aula'
        verbose_name_plural = 'Aulas'
        ordering = ['number']


class Material(models.Model):

    name = models.CharField('Nome', max_length=100)
    embedded = models.TextField('Vídeo embedded', blank=True)
    file = models.FileField(upload_to='lessons/materials', blank=True, null=True)

    lesson = models.ForeignKey(Lesson, verbose_name='Aula', related_name='materials')

    def is_embedded(self):
        return bool(self.embedded)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Material'
        verbose_name_plural = 'Materiais'


class Enrollment(models.Model):

    STATUS_CHOICES = (
        (0, 'Pendente'),
        (1, 'Aprovado'),
        (2, 'Cancelado'),
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='Usuário',
        related_name='enrollments'
    )
    turma = models.ForeignKey(
        Turma, verbose_name='Turma', related_name='enrollments'
    )
    status = models.IntegerField(
        'Situação', choices=STATUS_CHOICES, default=1, blank=True
    )

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def active(self):
        self.status = 1
        self.save()

    def is_approved(self):
        return self.status == 1

    class Meta:
        verbose_name = 'Inscrição'
        verbose_name_plural = 'Inscrições'
        unique_together = (('user', 'turma'),)


class Announcement(models.Model):

    turma = models.ForeignKey(
        Turma, verbose_name='Turma', related_name='announcements'
    )
    title = models.CharField('Título', max_length=100)
    content = models.TextField('Conteúdo')

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Anúncio'
        verbose_name_plural = 'Anúncios'
        ordering = ['-created_at']


class Comment(models.Model):

    announcement = models.ForeignKey(
        Announcement, verbose_name='Anúncio', related_name='comments'
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='usuário')
    comment = models.TextField('Comentário')

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    class Meta:
        verbose_name = 'Comentário'
        verbose_name_plural = 'Comentários'
        ordering = ['created_at']


def post_save_announcement(instance, created, **kwargs):
    if created:
        subject = instance.title
        context = {
            'announcement': instance
        }
        template_name = 'turmas/announcement_mail.html'
        enrollments = Enrollment.objects.filter(
            turma=instance.turma, status=1
        )
        for enrollment in enrollments:
            recipient_list = [enrollment.user.email]
            send_mail_template(subject, template_name, context, recipient_list)

models.signals.post_save.connect(
    post_save_announcement, sender=Announcement,
    dispatch_uid='post_save_announcement'
)

avasolos/turmas/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings

from avasolos.core.mail import send_mail_template

from .models import Comment


class ContactTurma(forms.Form):

    name = forms.CharField(label='Nome', max_length=100)
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(
        label='Mensagem/Dúvida', widget=forms.Textarea
    )

    def send_mail(self, turma):
        subject = '[%s] Contato' % turma
        context = {
            'name': self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message'],
        }
        template_name = 'turmas/contact_email.html'
        send_mail_template(
            subject, template_name, context, [settings.CONTACT_EMAIL]
        )

    # Envio antigo, sem o uso de template
    # def send_mail(self, turma):
    #     subject = '[%s] Contato' % turma
    #     message = 'Nome: %(name)s;E-mail: %(email)s;%(message)s'
    #     context = {
    #         'name': self.cleaned_data['name'],
    #         'email': self.cleaned_data['email'],
    #         'message': self.cleaned_data['message'],
    #     }
    #     message = message % context
    #     send_mail(
    #         subject, message, settings.DEFAULT_FROM_EMAIL,
    #         [settings.CONTACT_EMAIL]
    #     )


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['comment']

avasolos/turmas/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Turma, Enrollment, Announcement, Lesson, Material
from .forms import ContactTurma, CommentForm
from .decorators import enrollment_required

def index(request):
    turmas = Turma.objects.all()
    template_name = 'turmas/index.html'
    context = {
        'turmas': turmas
    }
    return render(request, template_name, context)

# def details(request, pk):
#     turma = get_object_or_404(Turma, pk=pk)
#     context = {
#         'turma': turma
#     }
#     template_name = 'turmas/details.html'
#     return render(request, template_name, context)

def details(request, slug):
    turma = get_object_or_404(Turma, slug=slug)
    context = {}
    if request.method == 'POST':
        form = ContactTurma(request.POST)
        if form.is_valid():
            context['is_valid'] = True
            form.send_mail(turma)
            form = ContactTurma()
    else:
        form = ContactTurma()
    context['form'] = form
    context['turma'] = turma
    template_name = 'turmas/details.html'
    return render(request, template_name, context)

@login_required
def enrollment(request, slug):
    turma = get_object_or_404(Turma, slug=slug)
    enrollment, created = Enrollment.objects.get_or_create(
        user=request.user, turma=turma
    )
    if created:
        # enrollment.active()
        messages.success(request, 'Você foi inscrito na turma com sucesso')
    else:
        messages.info(request, 'Você já está inscrito na turma')

    return redirect('accounts:dashboard')

@login_required
def undo_enrollment(request, slug):
    turma = get_object_or_404(Turma, slug=slug)
    enrollment = get_object_or_404(
        Enrollment, user=request.user, turma=turma
    )
    if request.method == 'POST':
        enrollment.delete()
        messages.success(request, 'Sua inscrição foi cancelada com sucesso')
        return redirect('accounts:dashboard')
    template = 'turmas/undo_enrollment.html'
    context = {
        'enrollment': enrollment,
        'turma': turma,
    }
    return render(request, template, context)

@login_required
@enrollment_required
def announcements(request, slug):
    turma = request.turma
    template = 'turmas/announcements.html'
    context = {
        'turma': turma,
        'announcements': turma.announcements.all()
    }
    return render(request, template, context)

@login_required
@enrollment_required
def show_announcement(request, slug, pk):
    turma = request.turma
    announcement = get_object_or_404(turma.announcements.all(), pk=pk)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.announcement = announcement
        comment.save()
        form = CommentForm()
        messages.success(request, 'Seu comentário foi enviado com sucesso')
    template = 'turmas/show_announcement.html'
    context = {
        'turma': turma,
        'announcement': announcement,
        'form': form,
    }
    return render(request, template, context)

@login_required
@enrollment_required
def lessons(request, slug):
    turma = request.turma
    template = 'turmas/lessons.html'
    lessons = turma.release_lessons()
    if request.user.is_staff:
        lessons = turma.lessons.all()
    context = {
        'turma': turma,
        'lessons': lessons
    }
    return render(request, template, context)

@login_required
@enrollment_required
def lesson(request, slug, pk):
    turma = request.turma
    lesson = get_object_or_404(Lesson, pk=pk, turma=turma)
    if not request.user.is_staff and not lesson.is_available():
        messages.error(request, 'Esta aula não está disponível')
        return redirect('turmas:lessons', slug=turma.slug)
    template = 'turmas/lesson.html'
    context = {
        'turma': turma,
        'lesson': lesson
    }
    return render(request, template, context)

@login_required
@enrollment_required
def material(request, slug, pk):
    turma = request.turma
    material = get_object_or_404(Material, pk=pk, lesson__turma=turma)
    lesson = material.lesson
    if not request.user.is_staff and not lesson.is_available():
        messages.error(request, 'Este material não está disponível')
        return redirect('turmas:lesson', slug=turma.slug, pk=lesson.pk)
    if not material.is_embedded():
        return redirect(material.file.url)
    template = 'turmas/material.html'
    context = {
        'turma': turma,
        'lesson': lesson,
        'material': material,
    }
    return render(request, template, context)

avasolos/turmas/templates/turmas/announcement_mail.html
{{ announcement.content|linebreaks }}

avasolos/turmas/templates/turmas/announcements.html
{% extends "turmas/turma_dashboard.html" %}

{% block dashboard_content %}
{% for announcement in announcements %}
<div class="well">
    <h2>
        <a href="{% url 'turmas:show_announcement' turma.slug announcement.pk %}">{{ announcement.title }}</a>
    </h2>
    {{ announcement.content|linebreaks }}
    <p>
        <a href="{% url 'turmas:show_announcement' turma.slug announcement.pk %}#comments">
        <i class="fa fa-comments-o"></i>
        {% with comments_count=announcement.comments.count %}
        {{ comments_count }}
        Comentário{{ comments_count|pluralize }}
        {% endwith %}
        </a>
    </p>
</div>
{% empty %}
<div class="well">
    <h2>Nenhum anúncio criado</h2>
</div>
{% endfor %}
{% endblock %}

avasolos/turmas/templates/turmas/contact_email.html
<p><strong>Nome</strong>: {{ name }}</p>
<p><strong>E-mail</strong>: {{ email }}</p>
{{ message|linebreaks }}

avasolos/turmas/templates/turmas/details.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    {{ turma }}
                </h1>
                <h2 class="splash-subhead">
                    {{ turma.description }}
                </h2>
                <p>
                    <a href="{% url 'turmas:enrollment' turma.slug %}" class="pure-button primary-button">Inscreva-se</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Sobre a Turma</h4>
            {{ turma.about|linebreaks }}
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            {% if turma.image %}
            <img src="{{ turma.image.url }}" alt="" />
            {% else %}
            <img src="{% static 'img/turma-image.png' %}" alt="" />
            {% endif %}
            <h4>Dúvidas?</h4>
            <p>
                <a href="#contato" title="" class="pure-button">Fale Conosco</a>
            </p>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon" id="contato">
    <div class="pure-u-1">
        <h3>Tire sua dúvida sobre a Turma</h3>
        {% if is_valid %}
        <p>Você enviou o formulário com sucesso</p>
        {% endif %}
        <form action="#contato" class="pure-form pure-form-aligned" method="post">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                    <ul class="errorlist">
                        {% for error in field.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

avasolos/turmas/templates/turmas/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <h4 class="content-subhead">Listagem de Turmas do AVA Solos</h4>
            <p>Abaixo a lista de turmas disponíveis na plataforma</p>
        </div>
    </div>
</div>
{% for turma in turmas %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <a href="{{ turma.get_absolute_url }}">
            {% if turma.image %}
            <img src="{{ turma.image.url }}" alt="{{ turma.name }}" />
            {% else %}
            <img src="{% static 'img/turma-image.png' %}" alt="{{ turma.name }}" />
            {% endif %}
            </a>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead"><a href="{{ turma.get_absolute_url }}" title="">{{ turma.name }}</a></h4>
            {{ turma.description|linebreaks }}
        </div>
    </div>
</div>
{% empty %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <p>Nenhuma turma está disponível na plataforma</p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

avasolos/turmas/templates/turmas/lesson.html
{% extends "turmas/turma_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'turmas:lessons' turma.slug %}">Aulas</a></li>
    <li>/</li>
    <li><a href="{% url 'turmas:lesson' turma.slug lesson.pk %}">{{ lesson }}</a></li>
{% endblock %}

{% block dashboard_content %}
<div class="well">
    <h2><a href="{% url 'turmas:lesson' turma.slug lesson.pk %}">{{ lesson }}</a></h2>
    {{ lesson.description|linebreaks }}
    <p>
        <h4>Material da Aula</h4>
        <table class="pure-table full">
            <thead>
                <tr>
                    <th>
                        Nome
                    </th>
                    <th>
                        Ação
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for material in lesson.materials.all %}
                <tr class="{% cycle '' 'pure-table-odd' %}">
                    <td>
                        {{ material }}
                    </td>
                    <td>
                        {% if material.is_embedded %}
                        <a href="{% url 'turmas:material' turma.slug material.pk %}">
                            <i class"fa fa-video-camera"></i>
                            Acessar
                        </a>
                        {% else %}
                        <a target="_blank" href="{{ material.file.url }}">
                            <i class"fa fa-download"></i>
                            Baixar
                        </a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </p>
</div>
{% endblock %}

avasolos/turmas/templates/turmas/lessons.html
{% extends "turmas/turma_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'turmas:lessons' turma.slug %}">Aulas</a></li>
{% endblock %}

{% block dashboard_content %}
{% for lesson in lessons %}
<div class="well">
    <h2><a href="{% url 'turmas:lesson' turma.slug lesson.pk %}">{{ lesson }}</a></h2>
    <p>
        {{ lesson.description|truncatewords:'20' }}
        <br />
        <a href="{% url 'turmas:lesson' turma.slug lesson.pk %}" title="">
        <i class="fa fa-eye"></i>
        Acessar Aula
        </a>
    </p>
</div>
{% empty %}
<div class="well">
    <h2>
        Nenhuma aula disponível.
    </h2>
</div>
{% endfor %}
{% endblock %}

avasolos/turmas/templates/turmas/material.html
{% extends "turmas/turma_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'turmas:lessons' turma.slug %}">Aulas</a></li>
    <li>/</li>
    <li><a href="{% url 'turmas:lesson' turma.slug lesson.pk %}">{{ lesson }}</a></li>
    <li>/</li>
    <li><a href="{% url 'turmas:material' turma.slug material.pk %}">{{ material }}</a></li>
{% endblock %}

{% block dashboard_content %}
<div class="well">
    <h2><a href="{% url 'turmas:material' turma.slug material.pk %}">{{ material }}</a></h2>
    {{ material.embedded|safe }}
    <p>
        <a href="{% url 'turmas:lesson' turma.slug lesson.pk %}">Voltar</a>
    </p>
</div>
{% endblock %}

avasolos/turmas/templates/turmas/show_announcement.html
{% extends "turmas/turma_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'turmas:show_announcement' turma.slug announcement.pk %}">{{ announcement }}</a></li>
{% endblock %}

{% block dashboard_content %}
    <div class="well">
        <h2>{{ announcement.title }}</h2>
        {{ announcement.content|linebreaks }}
    </div>
    <div class="well">
        <h4 id="comments">Comentários
        <a class="fright" href="#add_comment">Comentar</a></h4>
        <hr />
        {% for comment in announcement.comments.all %}
        <p>
            <strong>{{ comment.user }}</strong> disse à {{ comment.created_at|timesince }} atrás: <br />
            {{ comment.comment|linebreaksbr }}
        </p>
        <hr>
        {% empty %}
        <p>
            Nenhum comentário para este anúncio.
        </p>
        {% endfor %}
        <form method="post" class="pure-form pure-form-stacked" id="add_comment">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

avasolos/turmas/templates/turmas/turma_dashboard.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'turmas:announcements' turma.slug %}">{{ turma }}</a></li>
{% endblock %}

{% block menu_options %}
<li class="pure-menu-heading">
    {{ turma }}
</li>
<li>
    <a href="{% url 'turmas:lessons' turma.slug %}">
        <i class="fa fa-video-camera"></i>
        Aulas e Materiais
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-info-circle"></i>
        Informações
    </a>
</li>
<li>
    <a href="{% url 'turmas:announcements' turma.slug %}">
        <i class="fa fa-envelope"></i>
        Anúncios
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-comments"></i>
        Fórum de Dúvidas
    </a>
</li>
{{ block.super }}
{% endblock %}

avasolos/turmas/templates/turmas/undo_enrollment.html
{% extends 'turmas/turma_dashboard.html' %}

{% block dashboard_content %}
<form action="" method="post">
    {% csrf_token %}
    <h3>Você deseja realmente cancelar a inscrição desta turma?</h3>
    <div class="pure-controls">
        <button type="submit" class="pure-button pure-button-primary">Confirmar</button>
        <a href="{% url 'turmas:announcements' turma.slug %}" class="pure-button">Voltar</a>
    </div>
</form>
{% endblock %}